name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache .NET Core packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.csproj') }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Save build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifacts
          path: ./build-output

  test:
    name: Test
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache .NET Core packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.csproj') }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: Build Artifacts
          path: ./build-output

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal

      - name: Upload test artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Test Results
          path: TestResults
